apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - name: php
      port: 80
      nodePort: 30080
  type: NodePort 
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - name: database
      port: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      port: 80
      nodePort: 30090
  type: NodePort